ci

diff --git a/jenkinsfileagentes.ci b/jenkinsfileagentes.ci
--- a/jenkinsfileagentes.ci
+++ b/jenkinsfileagentes.ci
@@ -12,6 +12,7 @@ pipeline {
             agent { label 'python-agent' } 
             steps {
                 sh '''
+                   'echo "Estoy en la máquina: $(hostname) con el usuario: $(whoami)"'
                     pip install flake8 bandit
                     flake8 src/
                     bandit -r src/
@@ -20,44 +21,58 @@ pipeline {
         }
 
         
-        stage('Deploy Staging') {
-            agent any 
-            steps {
-                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials']]) {
-                    sh '''
-                        sam build
-                        sam deploy --config-env staging --no-confirm-changeset --no-fail-on-empty-changeset
-                        
-                        # SOLUCIÓN: Extraer la URL y guardarla en un archivo
-                        aws cloudformation describe-stacks \
-                            --stack-name ${APP_NAME}-staging \
-                            --query 'Stacks[0].Outputs[?OutputKey==`ServiceEndpoint`].OutputValue' \
-                            --output text > api_url.txt
-                    '''
-                }
-                
-                archiveArtifacts artifacts: 'api_url.txt', onlyIfSuccessful: true
-            }
-        }
+                  stage('Deploy Staging') {
+                  agent any 
+                  steps {
+                      withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials']]) {
+                          sh '''
+                              
+                              sam build
+                              sam deploy --config-env staging --no-confirm-changeset --no-fail-on-empty-changeset
+                              
+                            
+                              
+                              URL=$(aws cloudformation describe-stacks \
+                                  --stack-name todo-list-aws-staging \
+                                  --query "Stacks[0].Outputs[?OutputKey=='BaseUrlApi'].OutputValue" \
+                                  --output text)
+                              
+                              
+                              echo $URL > api_url.txt
+                              echo "Despliegue completado. URL capturada: $URL"
+                          '''
+                      }
+                      
+                      
+                      archiveArtifacts artifacts: 'api_url.txt', onlyIfSuccessful: true
+    }
+}
 
         
-        stage('API Rest Tests') {
-            agent { label 'test-agent' } 
-            steps {
-                
-                copyArtifacts projectName: env.JOB_NAME, selector: lastSuccessful(), filter: 'api_url.txt'
-                
-                script {
-                    def API_URL = readFile('api_url.txt').trim()
-                    echo "Probando la API en: ${API_URL}"
+                    stage('API Rest Tests') {
+                      
+                  agent { label 'test-agent' }
+                  steps {
+                  sh 'echo "Ahora estoy en una máquina distinta: $(hostname)"'
+                      copyArtifacts projectName: env.JOB_NAME, selector: lastSuccessful(), filter: 'api_url.txt'
+                      script {
                     
-                    sh """
-                        
-                        curl -s -o /dev/null -w "%{http_code}" ${API_URL}/todos | grep "200"
-                    """
-                }
-            }
+                    def BASE_URL = readFile('api_url.txt').trim()
+                    
+                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials']]) {
+                        sh """
+                            export BASE_URL=${BASE_URL}
+                           
+                            if [ "\$BASE_URL" = "None" ] || [ -z "\$BASE_URL" ]; then
+                                echo "ERROR: No se pudo obtener la URL"
+                                exit 1
+                            fi
+                            pip install pytest requests
+                            python3 -m pytest tests/unit/  # O tus tests de integración
+            """
         }
+    }
+}
 
         
         stage('Promote to Master') {
